Try manually caching nix store

diff --git a/.github/workflows/build/linux/action.yml b/.github/workflows/build/linux/action.yml
--- a/.github/workflows/build/linux/action.yml
+++ b/.github/workflows/build/linux/action.yml
@@ -10,23 +10,39 @@ runs:
   using: "composite"
   steps:
 
-  # - uses: cachix/install-nix-action@v15
-  #   with:
-  #     nix_path: nixpkgs=channel:${{ env.nixOSVersion }}
+  - name: Create nix store
+    run: |
+      # Create with liberal rights, otherwise cache action will complain
+      # about permission errors.
+      sudo mkdir -p /nix/store
+      sudo chmod -R 777 /nix
 
-  - name: Cache install Nix packages
-    uses: rikhuijzer/cache-install@v1.0.9
+  - name: Load nix cache
+    uses: actions/cache
     with:
-      key: nix-${{ hashFiles('flake.nix') }}
-      nix_file: 'shell.nix'
+      path: |
+        /nix/store/**
+        /nix/var/nix/*/*
+        /nix/var/nix/db/*
+        /nix/var/nix/db/*/**
+        !/nix/var/nix/daemon-socket/socket
+        !/nix/var/nix/userpool/*
+        !/nix/var/nix/gc.lock
+        !/nix/var/nix/db/big-lock
+        !/nix/var/nix/db/reserved
+      key: ${{ runner.os }}-${ inputs.target }}-cache
 
-  # - name: Install cachix
-  #   shell: bash
-  #   run: |
-  #     set -ex
+  - uses: cachix/install-nix-action@v15
+    with:
+      nix_path: nixpkgs=channel:nixos-unstable
 
-  #     mkdir -p .config/cachix
-  #     nix-env -iA cachix -f https://cachix.org/api/v1/install
+  - name: Install cachix
+    shell: bash
+    run: |
+      set -ex
+
+      mkdir -p .config/cachix
+      nix-env -iA cachix -f https://cachix.org/api/v1/install
 
   - name: Build
     shell: bash
